import 'package:flutter_riverpod/flutter_riverpod.dart';

enum AppLang { en, vi }

final langProvider = StateProvider<AppLang>((ref) => AppLang.en);

typedef TFunc = String Function(String key);

final tProvider = Provider<TFunc>((ref) {
  final lang = ref.watch(langProvider);
  final map = _dict[lang] ?? _dict[AppLang.en]!;
  return (String key) => map[key] ?? key;
});

const Map<AppLang, Map<String, String>> _dict = {
  AppLang.en: {
    'homepage.title': 'Online Wedding E-Card',
    'homepage.cta.templates': 'Templates',
    'homepage.cta.my_cards': 'My Cards',
    'homepage.cta.sign_in': 'Sign In',
    'intro.line': 'Create beautiful wedding cards, fast, your style',
    'carousel.see_details': 'See details',
    'templates.title': 'Template Library',
    'my_cards.title': 'My Cards',
    'common.load_more': 'Load more',
    'common.limit': 'Limit',
    'guests.title': 'Guests',
    'guests.total_gift': 'Total gift',
    'guests.add': 'Add',
    'album.title': 'Wedding Photos',
    'album.upload': 'Upload Photo',
    'common.error': 'Error',
    'subscription.title': 'Plans',
    'subscription.current_plan': 'Current Plan',
    'subscription.choose': 'Choose Plan',
    'subscription.recent_invoices': 'Recent Invoices',
    'subscription.amount': 'Amount',
    'subscription.note': 'Note',
    'subscription.date': 'Created at',
    'admin.manage': 'Manage Invitation',
    'admin.tabs.guests': 'Guests',
    'admin.tabs.gifts': 'Gifts',
    'admin.tabs.messages': 'Messages',
    'admin.public': 'Public',
    'admin.slug': 'Couple slug',
    'admin.save_slug': 'Save slug',
    'admin.qr_default': 'Default QR',
    'design.map': 'Map',
    'design.album': 'Photo Album',
    'design.countdown': 'Countdown',
    'design.preview': 'Preview',
    'countdown.days': 'days',
    'countdown.hours': 'hours',
    'countdown.minutes': 'minutes',
    'public.seo_desc': 'Wedding e-card of',
    'gift.box': 'Gift Box',
    'rsvp.title': 'RSVP',
    'rsvp.bride': 'Bride side',
    'rsvp.groom': 'Groom side',
    'rsvp.attending_yes': 'Attending',
    'rsvp.attending_no': 'Not attending',
    'rsvp.guests_count': 'Guests',
    'rsvp.note': 'Note',
    'rsvp.submit': 'Submit RSVP',
    'rsvp.invalid': 'Please enter your name',
    'checkout.title': 'Checkout',
    'checkout.open': 'Open Checkout',
    'checkout.info': 'We will open your checkout session.',
    'invoice.status': 'Status',
    'invoice.txid': 'Transaction ID',
    'admin.panel': 'Admin Control Panel',
    'admin.plans': 'Plans',
    'admin.billing': 'Billing',
    'plan.id': 'Plan ID',
    'plan.name': 'Plan Name',
    'plan.price': 'Price',
    'plan.period': 'Period',
    'plan.currency': 'Currency',
    'plan.price_id': 'Stripe Price ID',
    'plan.save': 'Save Plan',
    'billing.owner': 'Owner UID',
    'admin.locked': 'Admins only',
    'admin.grant': 'Grant Admin',
    'admin.revoke': 'Revoke Admin',
    'admin.granted': 'Admin granted',
    'admin.revoked': 'Admin revoked',
    'auth.sign_in': 'Sign In',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.register': 'Register',
    'auth.logout': 'Sign Out',
    'auth.google': 'Sign in with Google',
    'auth.facebook': 'Sign in with Facebook',
    'auth.hello': 'Hello',
    'auth.error': 'Error',
    'security.title': 'Security',
    'security.enable_2fa': 'Enable 2FA',
    'security.verify_enable': 'Verify & Enable',
    'security.code': '6-digit code',
    'security.verify': 'Verify 2FA',
    'security.register_key': 'Register Security Key',
    'security.enter_code': 'Enter code',
    'security.enabled': '2FA Enabled',
    'security.verified': '2FA Verified',
  },
  AppLang.vi: {
    'homepage.title': 'Thiệp cưới online',
    'homepage.cta.templates': 'Mẫu giao diện',
    'homepage.cta.my_cards': 'Thiệp của tôi',
    'homepage.cta.sign_in': 'Đăng nhập',
    'intro.line': 'Tạo thiệp cưới đẹp, nhanh, tùy biến theo phong cách',
    'carousel.see_details': 'Xem chi tiết mẫu',
    'templates.title': 'Thư viện Mẫu Thiệp',
    'my_cards.title': 'Thiệp của tôi',
    'common.load_more': 'Tải thêm',
    'common.limit': 'Giới hạn',
    'guests.title': 'Khách mời',
    'guests.total_gift': 'Tổng quà',
    'guests.add': 'Thêm',
    'album.title': 'Ảnh cưới',
    'album.upload': 'Tải ảnh lên',
    'common.error': 'Lỗi',
    'subscription.title': 'Gói dịch vụ',
    'subscription.current_plan': 'Gói hiện tại',
    'subscription.choose': 'Chọn gói',
    'subscription.recent_invoices': 'Hóa đơn gần đây',
    'subscription.amount': 'Số tiền',
    'subscription.note': 'Ghi chú',
    'subscription.date': 'Thời gian tạo',
    'admin.manage': 'Quản lý thiệp',
    'admin.tabs.guests': 'Khách mời',
    'admin.tabs.gifts': 'Quà mừng',
    'admin.tabs.messages': 'Lời nhắn',
    'admin.public': 'Công khai',
    'admin.slug': 'Slug cặp đôi',
    'admin.save_slug': 'Lưu slug',
    'admin.qr_default': 'QR mặc định',
    'design.map': 'Bản đồ',
    'design.album': 'Album ảnh',
    'design.countdown': 'Đếm ngược',
    'design.preview': 'Xem trước',
    'countdown.days': 'ngày',
    'countdown.hours': 'giờ',
    'countdown.minutes': 'phút',
    'public.seo_desc': 'Thiệp cưới của',
    'gift.box': 'Hộp quà',
    'rsvp.title': 'Xác nhận tham dự',
    'rsvp.bride': 'Nhà gái',
    'rsvp.groom': 'Nhà trai',
    'rsvp.attending_yes': 'Tham dự',
    'rsvp.attending_no': 'Không tham dự',
    'rsvp.guests_count': 'Số khách',
    'rsvp.note': 'Ghi chú',
    'rsvp.submit': 'Gửi RSVP',
    'rsvp.invalid': 'Vui lòng nhập tên',
    'checkout.title': 'Thanh toán',
    'checkout.open': 'Mở trang thanh toán',
    'checkout.info': 'Hệ thống sẽ mở phiên thanh toán của bạn.',
    'invoice.status': 'Trạng thái',
    'invoice.txid': 'Mã giao dịch',
    'admin.panel': 'Bảng điều khiển Admin',
    'admin.plans': 'Gói dịch vụ',
    'admin.billing': 'Thanh toán',
    'plan.id': 'Mã gói',
    'plan.name': 'Tên gói',
    'plan.price': 'Giá',
    'plan.period': 'Chu kỳ',
    'plan.currency': 'Tiền tệ',
    'plan.price_id': 'Stripe Price ID',
    'plan.save': 'Lưu gói',
    'billing.owner': 'UID chủ sở hữu',
    'admin.locked': 'Chỉ dành cho Admin',
    'admin.grant': 'Cấp quyền Admin',
    'admin.revoke': 'Thu hồi Admin',
    'admin.granted': 'Đã cấp quyền Admin',
    'admin.revoked': 'Đã thu hồi Admin',
    'auth.sign_in': 'Đăng nhập',
    'auth.email': 'Email',
    'auth.password': 'Mật khẩu',
    'auth.register': 'Đăng kí tài khoản',
    'auth.logout': 'Đăng xuất',
    'auth.google': 'Đăng nhập với Google',
    'auth.facebook': 'Đăng nhập với Facebook',
    'auth.hello': 'Xin chào',
    'auth.error': 'Lỗi',
    'security.title': 'Bảo mật',
    'security.enable_2fa': 'Bật 2FA',
    'security.verify_enable': 'Xác thực & Bật',
    'security.code': 'Mã 6 chữ số',
    'security.verify': 'Xác thực 2FA',
    'security.register_key': 'Đăng ký khóa bảo mật',
    'security.enter_code': 'Nhập mã',
    'security.enabled': 'Đã bật 2FA',
    'security.verified': 'Đã xác thực 2FA',
  },
};
