import 'package:flutter_riverpod/flutter_riverpod.dart';

enum AppLang { en, vi }

final langProvider = StateProvider<AppLang>((ref) => AppLang.en);

typedef TFunc = String Function(String key);

final tProvider = Provider<TFunc>((ref) {
  final lang = ref.watch(langProvider);
  final map = _dict[lang] ?? _dict[AppLang.en]!;
  return (String key) => map[key] ?? key;
});

const Map<AppLang, Map<String, String>> _dict = {
  AppLang.en: {
    'homepage.title': 'Online Wedding E-Card',
    'homepage.cta.templates': 'Templates',
    'homepage.cta.my_cards': 'My Cards',
    'homepage.cta.sign_in': 'Sign In',
    'intro.line': 'Create beautiful wedding cards, fast, your style',
    'carousel.see_details': 'See details',
    'templates.title': 'Template Library',
    'my_cards.title': 'My Cards',
    'common.load_more': 'Load more',
    'common.limit': 'Limit',
    'guests.title': 'Guests',
    'guests.total_gift': 'Total gift',
    'guests.add': 'Add',
    'album.title': 'Wedding Photos',
    'album.upload': 'Upload Photo',
    'common.error': 'Error',
    'subscription.title': 'Plans',
    'subscription.current_plan': 'Current Plan',
    'subscription.choose': 'Choose Plan',
    'subscription.recent_invoices': 'Recent Invoices',
    'subscription.amount': 'Amount',
    'subscription.note': 'Note',
    'subscription.date': 'Created at',
    'admin.manage': 'Manage Invitation',
    'admin.tabs.guests': 'Guests',
    'admin.tabs.gifts': 'Gifts',
    'admin.tabs.messages': 'Messages',
    'admin.public': 'Public',
    'admin.slug': 'Couple slug',
    'admin.save_slug': 'Save slug',
    'admin.qr_default': 'Default QR',
    'design.map': 'Map',
    'design.album': 'Photo Album',
    'design.countdown': 'Countdown',
    'design.preview': 'Preview',
    'countdown.days': 'days',
    'countdown.hours': 'hours',
    'countdown.minutes': 'minutes',
    'public.seo_desc': 'Wedding e-card of',
    'gift.box': 'Gift Box',
  },
  AppLang.vi: {
    'homepage.title': 'Thiệp cưới online',
    'homepage.cta.templates': 'Mẫu giao diện',
    'homepage.cta.my_cards': 'Thiệp của tôi',
    'homepage.cta.sign_in': 'Đăng nhập',
    'intro.line': 'Tạo thiệp cưới đẹp, nhanh, tùy biến theo phong cách',
    'carousel.see_details': 'Xem chi tiết mẫu',
    'templates.title': 'Thư viện Mẫu Thiệp',
    'my_cards.title': 'Thiệp của tôi',
    'common.load_more': 'Tải thêm',
    'common.limit': 'Giới hạn',
    'guests.title': 'Khách mời',
    'guests.total_gift': 'Tổng quà',
    'guests.add': 'Thêm',
    'album.title': 'Ảnh cưới',
    'album.upload': 'Tải ảnh lên',
    'common.error': 'Lỗi',
    'subscription.title': 'Gói dịch vụ',
    'subscription.current_plan': 'Gói hiện tại',
    'subscription.choose': 'Chọn gói',
    'subscription.recent_invoices': 'Hóa đơn gần đây',
    'subscription.amount': 'Số tiền',
    'subscription.note': 'Ghi chú',
    'subscription.date': 'Thời gian tạo',
    'admin.manage': 'Quản lý thiệp',
    'admin.tabs.guests': 'Khách mời',
    'admin.tabs.gifts': 'Quà mừng',
    'admin.tabs.messages': 'Lời nhắn',
    'admin.public': 'Công khai',
    'admin.slug': 'Slug cặp đôi',
    'admin.save_slug': 'Lưu slug',
    'admin.qr_default': 'QR mặc định',
    'design.map': 'Bản đồ',
    'design.album': 'Album ảnh',
    'design.countdown': 'Đếm ngược',
    'design.preview': 'Xem trước',
    'countdown.days': 'ngày',
    'countdown.hours': 'giờ',
    'countdown.minutes': 'phút',
    'public.seo_desc': 'Thiệp cưới của',
    'gift.box': 'Hộp quà',
  },
};
